<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Syncfusion.Blazor.Buttons" Version="28.2.5" />
    <PackageReference Include="Syncfusion.Blazor.Themes" Version="28.2.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ToDoListFunctionsTest\ToDoListFunctionsTest.csproj" />
    <ProjectReference Include="..\ToDoListFunctions\ToDoListFunctions.csproj" />
  </ItemGroup>

</Project>
